<?php
 
 /**
 * Implements hook_menu().
 */
function pagenotfound_menu() {
  $items = array();
  $items['pagenotfound'] = array(
    'title' => '404 Error',
    'page callback' => 'pagenotfound_output',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
} 
/**
 * Implements hook_theme().
 */
function pagenotfound_theme() {
  return array(
    'pagenotfound' => array(
      'variables' => array('page' => array()),
      'template' => 'pagenotfound',
    ),
  );
}
/**
 * Generate a custom login page
 * @see more in print_controller_html() in print.pages.inc of the Print module 
 */
function pagenotfound_output(){
	$page = _pagenotfound_output_prerequisite(); // get/prepare necessary variables, js, css for the page
	 $page['form'] = '';
    
    $html = theme('pagenotfound', array('page' => $page)); 

    drupal_add_http_header('Content-Type', 'text/html; charset=utf-8');
    drupal_send_headers();
    print $html; // cease Drupal page rendering and render directly to the browser
	
} 
/**
 * Prepare the array for the template with common details
 * @see more _print_var_generator() in print.pages.inc of the Print module
 */
function _pagenotfound_output_prerequisite(){
    global $base_url, $language; 
    $page = array();
    $page['language']   = $language->language;
    $page['head']       = drupal_get_html_head();
    $page['title']      = '';
    $page['scripts']    = drupal_get_js();
    $page['favicon']    = '';
    // if there is a custom css file for this page
    // drupal_add_css(drupal_get_path('module', 'pagenotfound') . '/css/mylogin.css');
    $page['css'] = drupal_get_css();
    $page['message'] = drupal_get_messages();
    $page['footer_scripts'] = drupal_get_js('footer');

    return $page;
} 
function pagenotfound_form_submit(&$form, &$form_state) {

die('My name is ' . $form_state['values']['query']);
  exit;
}
?>

